use_small_heuristics = "Max"
reorder_imports = true
edition = "2021"
# This option will merge imports, however it's only available in +nightly.
# imports_granularity = "Module"
# fn_args_density = "Compressed"
# overflow_delimited_expr = "true"
array_width = 40
chain_width = 40
fn_params_layout = "Vertical"
hard_tabs = false
max_width = 100
match_arm_leading_pipes = "Always"
use_field_init_shorthand = true